import json
import os

locales_dir = "apps/srt-gui/src/lib/i18n/locales"
locales = ["ar", "de", "es", "fr", "hi", "it", "ja", "ko", "pl", "pt", "ru", "tr", "zh"]

translations = {
    "shortcuts.action.alignSwapFiles": {
        "ar": "تبديل ترتيب الملفات",
        "de": "Dateireihenfolge tauschen",
        "es": "Intercambiar el orden de los archivos",
        "fr": "Échanger l'ordre des fichiers",
        "hi": "फ़ाइलों का क्रम बदलें",
        "it": "Scambia ordine file",
        "ja": "ファイルの順序を入れ替える",
        "ko": "파일 순서 바꾸기",
        "pl": "Zamień kolejność plików",
        "pt": "Trocar a ordem dos arquivos",
        "ru": "Поменять порядок файлов",
        "tr": "Dosya sırasını değiştir",
        "zh": "交换文件顺序"
    },
    "align.helpContent": {
        "ar": "<p>تم تصميم علامة التبويب هذه لـ <b>التحقق من الترجمات وتصحيحها</b> بسرعة ، مع سير عمل موجه جنبًا إلى جنب.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1st SRT</b> — تحميل ملف الترجمة الأساسي.</li><li><b>2nd SRT</b> — تحميل الملف الثاني.</li><li><b>التحميل الذكي</b> — بعد تحديد ملف واحد ، تحاول VESTA اكتشاف الترجمة المرافقة في نفس المجلد تلقائيًا.</li><li><b>الاقتران المستند إلى المعرف</b> — تتم محاذاة الخطوط بواسطة معرف الترجمة ؛ تتم إضافة الإدخالات المفقودة تلقائيًا حتى يظل كلا العمودين متزامنين.</li><li><b>تبديل الملفات</b> — يمكنك عكس ترتيب الملفات على الفور للمقارنة من منظور متعاكس.</li><li><b>التنقل السريع</b> — تحرك صفحة تلو الأخرى ، أو انتقل إلى الصفحة الأولى / الأخيرة ، أو انتقل مباشرة إلى الترجمات الفارغة لإكمال الترجمات المفقودة.</li><li><b>العمود الأيمن القابل للتحرير</b> — راجع النص الموجود في العمود الأيمن مع الاحتفاظ بسياق التوقيت من كلا المسارين.</li><li><b>التراجع والحفظ الآمن</b> — استخدم Ctrl+Z للتحرير الأخير وقم بتصدير ملف جديد بلاحقة مخصصة.</li></ul>",
        "de": "<p>Dieser Tab wurde entwickelt, um <b>Untertitel schnell zu überprüfen und zu korrigieren</b>, mit einem geführten Side-by-Side-Workflow.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1st SRT</b> — Die Basis-Untertiteldatei laden.</li><li><b>2nd SRT</b> — Die zweite Datei laden.</li><li><b>Intelligentes Laden</b> — Nach Auswahl einer Datei versucht VESTA automatisch, den passenden Untertitel im selben Ordner zu erkennen.</li><li><b>ID-basierte Kopplung</b> — Zeilen werden nach Untertitel-ID ausgerichtet; fehlende Einträge werden automatisch aufgefüllt, sodass beide Spalten synchron bleiben.</li><li><b>Dateien tauschen</b> — Kehren Sie die Dateireihenfolge sofort um, um sie aus der entgegengesetzten Perspektive zu vergleichen.</li><li><b>Schnelle Navigation</b> — Bewegen Sie sich seitenweise, springen Sie zur ersten/letzten Seite oder springen Sie direkt zu leeren Untertiteln, um fehlende Übersetzungen zu ergänzen.</li><li><b>Bearbeitbare rechte Spalte</b> — Überarbeiten Sie den Text in der rechten Spalte, während Sie den Zeitkontext beider Spuren beibehalten.</li><li><b>Rückgängig & sicheres Speichern</b> — Verwenden Sie Strg+Z für die letzten Änderungen und exportieren Sie eine neue Datei mit einem dedizierten Suffix.</li></ul>",
        "es": "<p>Esta pestaña está diseñada para <b>revisar y corregir subtítulos</b> rápidamente, con un flujo de trabajo en paralelo guiado.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1er SRT</b> — Carga el archivo de subtítulos base.</li><li><b>2º SRT</b> — Carga el segundo archivo.</li><li><b>Carga inteligente</b> — Después de seleccionar un archivo, VESTA intenta detectar automáticamente el subtítulo complementario en la misma carpeta.</li><li><b>Emparejamiento por ID</b> — Las líneas se alinean por ID de subtítulo; las entradas faltantes se rellenan automáticamente para que ambas columnas permanezcan sincronizadas.</li><li><b>Intercambiar archivos</b> — Invierte instantáneamente el orden de los archivos para comparar desde la perspectiva opuesta.</li><li><b>Navegación rápida</b> — Muévete página por página, salta a la primera/última página, o salta directamente a subtítulos vacíos para completar las traducciones faltantes.</li><li><b>Columna derecha editable</b> — Revisa el texto en la columna derecha manteniendo el contexto de tiempo de ambas pistas.</li><li><b>Deshacer y guardado seguro</b> — Usa Ctrl+Z para editar y exportar un nuevo archivo con un sufijo dedicado.</li></ul>",
        "fr": "<p>Cet onglet est conçu pour <b>vérifier et corriger les sous-titres</b> rapidement, avec un flux de travail côte à côte guidé.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1er SRT</b> — Charger le fichier de sous-titres de base.</li><li><b>2ème SRT</b> — Charger le deuxième fichier.</li><li><b>Chargement intelligent</b> — Après avoir sélectionné un fichier, VESTA essaie de détecter automatiquement le sous-titre compagnon dans le même dossier.</li><li><b>Appariement basé sur l'ID</b> — Les lignes sont alignées par ID de sous-titre ; les entrées manquantes sont complétées automatiquement pour que les deux colonnes restent synchronisées.</li><li><b>Échanger les fichiers</b> — Inversez instantanément l'ordre des fichiers pour comparer à partir de la perspective opposée.</li><li><b>Navigation rapide</b> — Déplacez-vous page par page, passez à la première/dernière page, ou passez directement aux sous-titres vides pour compléter les traductions manquantes.</li><li><b>Colonne droite modifiable</b> — Révisez le texte dans la colonne de droite tout en préservant le contexte temporel des deux pistes.</li><li><b>Annulation et sauvegarde sécurisée</b> — Utilisez Ctrl+Z pour les modifications récentes et exportez un nouveau fichier avec un suffixe dédié.</li></ul>",
        "hi": "<p>यह टैब <b>उपशीर्षक को जल्दी से जांचने और सही करने</b> के लिए डिज़ाइन किया गया है, एक निर्देशित अगल-बगल कार्यप्रवाह के साथ।</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1st SRT</b> — आधार उपशीर्षक फ़ाइल लोड करें।</li><li><b>2nd SRT</b> — दूसरी फ़ाइल लोड करें।</li><li><b>स्मार्ट लोडिंग</b> — एक फ़ाइल का चयन करने के बाद, VESTA स्वचालित रूप से उसी फ़ोल्डर में साथी उपशीर्षक का पता लगाने का प्रयास करता है।</li><li><b>ID-आधारित पेयरिंग</b> — पंक्तियों को उपशीर्षक ID द्वारा संरेखित किया जाता है; गायब प्रविष्टियों को स्वचालित रूप से पैड किया जाता है ताकि दोनों कॉलम सिंक में रहें।</li><li><b>फ़ाइलें स्वैप करें</b> — विपरीत परिप्रेक्ष्य से तुलना करने के लिए तुरंत फ़ाइल क्रम को उल्टा करें।</li><li><b>तेज नेविगेशन</b> — पृष्ठ-दर-पृष्ठ जाएं, पहले/अंतिम पृष्ठ पर जाएं, या गायब अनुवादों को पूरा करने के लिए सीधे खाली उपशीर्षक पर जाएं।</li><li><b>संपादन योग्य दायां कॉलम</b> — दोनों पटरियों से समय संदर्भ को संरक्षित करते हुए दाएं कॉलम में पाठ को संशोधित करें।</li><li><b>पूर्ववत करें और सुरक्षित सहेजें</b> — हाल के संपादन के लिए Ctrl+Z का उपयोग करें और एक समर्पित प्रत्यय के साथ एक नई फ़ाइल निर्यात करें।</li></ul>",
        "it": "<p>Questa tab serve a <b>controllare e correggere i sottotitoli</b> in modo rapido, con un flusso di lavoro affiancato.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1st SRT</b> — Carica il file di sottotitoli di base.</li><li><b>2nd SRT</b> — Carica il secondo file.</li><li><b>Caricamento intelligente</b> — Dopo la selezione di un file, VESTA prova a trovare automaticamente il compagno nella stessa cartella.</li><li><b>Accoppiamento per ID</b> — Le righe vengono allineate per numero di sottotitolo; le voci mancanti vengono aggiunte automaticamente per mantenere le due colonne sincronizzate.</li><li><b>Scambia file</b> — Inverti istantaneamente l'ordine dei file per confrontare dalla prospettiva opposta.</li><li><b>Navigazione rapida</b> — Scorri pagina per pagina, salta alla prima/ultima pagina o vai direttamente ai sottotitoli vuoti per completare le traduzioni mancanti.</li><li><b>Colonna destra modificabile</b> — Correggi il testo nella colonna di destra, conservando il riferimento temporale di entrambe le tracce.</li><li><b>Annulla e salva sicura</b> — Usa Ctrl+Z per annullare modifiche recenti ed esporta un nuovo file con un suffisso dedicato.</li></ul>",
        "ja": "<p>このタブは、ガイド付きのサイドバイサイドワークフローで<b>字幕をすばやく確認して修正する</b>ように設計されています。</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1番目の SRT</b> — ベース字幕ファイルを読み込みます。</li><li><b>2番目の SRT</b> — 2番目のファイルを読み込みます。</li><li><b>スマート ロード</b> — 1つのファイルを選択すると、VESTA は同じフォルダー内の関連する字幕を自動検出しようとします。</li><li><b>ID ベースのペアリング</b> — 行は字幕 ID によって配置されます。不足しているエントリは自動的に埋め込まれるため、両方の列が同期されます。</li><li><b>ファイルの入れ替え</b> — ファイルの順序を瞬時に反転させて、反対の視点から比較します。</li><li><b>高速ナビゲーション</b> — ページごとに移動するか、最初/最後のページにジャンプするか、空の字幕に直接ジャンプして不足している翻訳を完了させます。</li><li><b>編集可能な右列</b> — 両方のトラックのタイミング コンテキストを維持したまま、右列のテキストを修正します。</li><li><b>元に戻すと安全な保存</b> — 最近の編集には Ctrl+Z を使用し、専用のサフィックスを付けて新しいファイルを書き出します。</li></ul>",
        "ko": "<p>이 탭은 안내하는 나란히 워크플로를 통해 <b>자막을 빠르게 확인하고 수정</b>하도록 설계되었습니다.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>첫 번째 SRT</b> — 기본 자막 파일을 로드합니다.</li><li><b>두 번째 SRT</b> — 두 번째 파일을 로드합니다.</li><li><b>스마트 로딩</b> — 하나의 파일을 선택하면 VESTA가 동일한 폴더에서 동반 자막을 자동으로 감지하려고 시도합니다.</li><li><b>ID 기반 페어링</b> — 자막 ID에 따라 선이 정렬됩니다. 누락된 항목은 두 열이 동기화 상태를 유지하도록 자동으로 채워집니다.</li><li><b>파일 교체</b> — 반대 관점에서 비교하기 위해 파일 순서를 즉시 반전시킵니다.</li><li><b>빠른 탐색</b> — 페이지별로 이동하거나, 첫/마지막 페이지로 점프하거나, 빈 자막으로 직접 점프하여 누락된 번역을 완료합니다.</li><li><b>편집 가능한 오른쪽 열</b> — 두 트랙의 타이밍 컨텍스트를 유지하면서 오른쪽 열의 텍스트를 수정합니다.</li><li><b>실행 취소 및 안전한 저장</b> — 최근 편집을 위해서는 Ctrl+Z를 사용하고 전용 접미사가 있는 새 파일을 내보냅니다.</li></ul>",
        "pl": "<p>Ta karta służy do <b>szybkiego sprawdzania i poprawiania napisów</b> w układzie obok siebie.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>Pierwszy SRT</b> — Wczytaj bazowy plik z napisami.</li><li><b>Drugi SRT</b> — Wczytaj drugi plik.</li><li><b>Inteligentne wczytywanie</b> — Po wybraniu jednego pliku VESTA próbuje automatycznie wykryć towarzyszące napisy w tym samym folderze.</li><li><b>Parowanie według ID</b> — Wiersze są wyrównywane według identyfikatora; brakujące wpisy są automatycznie uzupełniane, dzięki czemu obie kolumny są zsynchronizowane.</li><li><b>Zamień pliki</b> — Błyskawicznie odwróć kolejność plików, aby porównać z odwrotnej perspektywy.</li><li><b>Szybka nawigacja</b> — Przewijaj strona po stronie, skacz do pierwszej/ostatniej lub przejdź bezpośrednio do pustych miejsc, aby uzupełnić tłumaczenia.</li><li><b>Edytowalna prawa kolumna</b> — Poprawiaj tekst po prawej stronie, zachowując czasy z obu plików.</li><li><b>Cofanie i bezpieczny zapis</b> — Użyj Ctrl+Z by cofnąć i eksportuj nowy plik ze specjalnym sufiksem.</li></ul>",
        "pt": "<p>Esta aba foi desenvolvida para <b>verificar e corrigir legendas</b> rapidamente, com um fluxo lado-a-lado.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1º SRT</b> — Carregue o arquivo de base.</li><li><b>2º SRT</b> — Carregue o segundo arquivo.</li><li><b>Carregamento inteligente</b> — Ao selecionar um arquivo, o VESTA tenta achar automaticamente a legenda correspondente na mesma pasta.</li><li><b>Pareamento por ID</b> — As linhas são alinhadas pelo ID; entradas faltando são preenchidas para manter as colunas sincronizadas.</li><li><b>Inverter arquivos</b> — Inverta a ordem para comparar pela perspectiva oposta.</li><li><b>Navegação rápida</b> — Mova-se página por página, pule para o início/fim ou encontre rapidamente falas vazias.</li><li><b>Coluna direita editável</b> — Revise o texto na direita mantendo os tempos de ambas.</li><li><b>Desfazer e salvamento seguro</b> — Use Ctrl+Z para desfazer, e exporte um arquivo novo com sufixo especial.</li></ul>",
        "ru": "<p>Эта вкладка предназначена для <b>быстрой проверки и исправления субтитров</b> с помощью удобного параллельного интерфейса.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1-й SRT</b> — Загрузите базовый файл субтитров.</li><li><b>2-й SRT</b> — Загрузите второй файл.</li><li><b>Умная загрузка</b> — После выбора одного файла VESTA автоматически попытается найти пару в той же папке.</li><li><b>Связывание по ID</b> — Строки выравниваются по номеру; пропущенные реплики автоматически заполняются, чтобы столбцы не рассинхронизировались.</li><li><b>Поменять файлы</b> — Мгновенно меняйте порядок файлов для сравнения.</li><li><b>Быстрая навигация</b> — Листайте по страницам, переходите в начало/конец или ищите пустые субтитры.</li><li><b>Редактируемый правый столбец</b> — Редактируйте текст справа, сохраняя тайминги обеих дорожек.</li><li><b>Отмена и безопасное сохранение</b> — Используйте Ctrl+Z для отмены и экспортируйте готовый файл с суффиксом.</li></ul>",
        "tr": "<p>Bu sekme, yan yana çalışma akışı ile <b>altyazıları hızlıca kontrol edip düzeltmek</b> için tasarlandı.</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>1. SRT</b> — Temel altyazı dosyasını yükleyin.</li><li><b>2. SRT</b> — İkinci dosyayı yükleyin.</li><li><b>Akıllı yükleme</b> — Dosya seçtikten sonra VESTA aynı klasördeki eşleşen altyazıyı otomatik bulmaya çalışır.</li><li><b>Kimlik tabanlı eşleştirme</b> — Satırlar altyazı numarasına göre hizalanır; eksikler otomatik doldurulur.</li><li><b>Dosyaları yer değiştir</b> — Zıt perspektiften karşılaştırmak için dosya sırasını çevirin.</li><li><b>Hızlı gezinme</b> — Sayfa sayfa ilerleyin, başa/sona atlayın ya da boş altyazılara gidin.</li><li><b>Düzenlenebilir sağ sütun</b> — Her iki dosyanın zamanlarını koruyarak sağdaki metni düzenleyin.</li><li><b>Geri al ve güvenli kaydet</b> — Ctrl+Z ile son değişiklikleri geri alın ve yeni dosyayı dışa aktarın.</li></ul>",
        "zh": "<p>此选项卡专为通过并排对比工作流来<b>快速检查和更正字幕</b>而设计。</p><ul class='list-disc pl-4 mt-2 space-y-1'><li><b>第一个 SRT</b> — 加载基础字幕文件。</li><li><b>第二个 SRT</b> — 加载第二个文件。</li><li><b>智能加载</b> — 选择一个文件后，VESTA 会尝试自动检测同一文件夹中的对应字幕。</li><li><b>基于 ID 配对</b> — 行按字幕 ID 对齐，自动填补充缺失条目以保持两列同步。</li><li><b>交换文件</b> — 瞬间反转文件顺序，从相反角度进行对比。</li><li><b>快速导航</b> — 翻页操作，可跳至首页/末页，或直接跳至空字幕完成缺失部分。</li><li><b>右侧列可编辑</b> — 在保留两侧时间轴上下文的同时修改右侧文本。</li><li><b>撤销与安全保存</b> — 使用 Ctrl+Z 撤销，导出带有专用后缀的新文件。</li></ul>"
    },
    "settings.customProviderTip": {
        "ar": "اتصل بأي نقطة نهاية متوافقة مع OpenAI (مثل OpenRouter و Together وما إلى ذلك). قم بتكوين عنوان URL ومفتاح API اختياري.",
        "de": "Verbinden Sie einen beliebigen OpenAI-kompatiblen Endpunkt (OpenRouter, Together usw.). Konfigurieren Sie URL und optionalen API-Schlüssel.",
        "es": "Conéctese a cualquier punto de conexión compatible con OpenAI (OpenRouter, Together, etc.). Configure la URL y la clave de API opcional.",
        "fr": "Connectez tout point de terminaison compatible OpenAI (OpenRouter, Together, etc.). Configurez l'URL et la clé API facultative.",
        "hi": "किसी भी OpenAI-संगत एंडपॉइंट (OpenRouter, Together आदि) से कनेक्ट करें। यूआरएल और वैकल्पिक API कुंजी कॉन्फ़िगर करें।",
        "it": "Connetti qualsiasi endpoint compatibile OpenAI (OpenRouter, Together, ecc.). Configura URL e chiave API opzionale.",
        "ja": "OpenAI 互換のエンドポイント (OpenRouter、Together など) に接続します。 URL とオプションの API キーを構成します。",
        "ko": "OpenAI 호환 엔드포인트(OpenRouter, Together 등)를 연결하세요. URL 및 선택적 API 키를 구성하세요.",
        "pl": "Połącz z dowolnym endpointem zgodnym z OpenAI (OpenRouter, Together itp.). Skonfiguruj URL i opcjonalny klucz API.",
        "pt": "Conecte-se a qualquer endpoint compatível com OpenAI (OpenRouter, Together, etc.). Configure URL e, se aplicável, chave API.",
        "ru": "Подключите любой OpenAI-совместимый API (OpenRouter, Together и т.д.). Укажите URL и при необходимости API-ключ.",
        "tr": "OpenAI uyumlu dilediğiniz uç noktayı bağlayın (OpenRouter, Together vb.). URL'yi ve isteğe bağlı API anahtarını yapılandırın.",
        "zh": "连接任何兼容 OpenAI 的 API 模型终端 (OpenRouter, Together 等)。输入您接口对的 URL，并视情况配置 API 密钥。"
    },
    "settings.groqProviderTip": {
        "ar": "استدلال فائق السرعة يتم تشغيله بواسطة Groq LPU. يتطلب مفتاح واجهة برمجة تطبيقات gsk_ من console.groq.com.",
        "de": "Ultraschnelle Inferenz auf Basis von Groq LPU. Erfordert einen gsk_ API-Schlüssel von console.groq.com.",
        "es": "Inferencia ultrarrápida impulsada por Groq LPU. Requiere una clave API gsk_ de console.groq.com.",
        "fr": "Inférence ultra-rapide optimisée par Groq LPU. Nécessite une clé API gsk_ à partir de console.groq.com.",
        "hi": "Groq LPU द्वारा संचालित अल्ट्रा-फास्ट अनुमान। console.groq.com से gsk_ API कुंजी की आवश्यकता होती है।",
        "it": "Inferenza ultra-veloce tramite Groq LPU. Richiede una chiave API gsk_ da console.groq.com.",
        "ja": "Groq LPU を活用した超高速推論。 console.groq.com から発行される gsk_ API キーが必要です。",
        "ko": "Groq LPU로 구동되는 초고속 추론. console.groq.com의 gsk_ API 키가 필요합니다.",
        "pl": "Ultraszybka inferencja zasilana przez Groq LPU. Wymaga klucza API gsk_ z console.groq.com.",
        "pt": "Inferência ultra rápida impulsionada por Groq LPU. Requer uma chave API gsk_ no console.groq.com.",
        "ru": "Сверхбыстрые вычисления на базе Groq LPU. Требуется API-ключ gsk_ от console.groq.com.",
        "tr": "Groq LPU ile çok hızlı çıkarım. console.groq.com adresinden alınan gsk_ API anahtarını gerektirir.",
        "zh": "采用 Groq LPU 提供支持超快推理。需要从 console.groq.com 获取的 gsk_ 格式 API 密钥。"
    }
}

for lang in locales:
    p = os.path.join(locales_dir, f"{lang}.json")
    if os.path.exists(p):
        with open(p, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        changed = False
        for k in translations.keys():
            if k in data and data[k] != translations[k][lang]:
                data[k] = translations[k][lang]
                changed = True
                
        if changed:
            with open(p, "w", encoding="utf-8", newline='\n') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
                f.write("\n")
            print(f"Updated {lang}.json")

