import json
import os

locales_dir = "apps/srt-gui/src/lib/i18n/locales"

translations = {
    "ar": {
        "align.baseSrt": "SRT الأصلي / الأساسي",
        "align.openSrt": "فتح SRT",
        "align.dragDropSrt": "اسحب وأفلت SRT هنا...",
        "align.subtitlesLoaded": "تم تحميل {{count}} ترجمة",
        "align.swapFiles": "تبديل ترتيب الملفات",
        "align.translationSrt": "الترجمة / مراجعة SRT",
        "align.loadPrompt": "قم بتحميل بعض ملفات SRT لبدء المحاذاة.",
        "align.dragDropAnywhere": "يمكنك سحب وإفلات الملفات في أي مكان في هذه النافذة.",
        "align.page": "الصفحة",
        "align.of": "من",
        "align.subsPerPage": "{{count}} ترجمات في الصفحة",
        "align.goToStart": "الذهاب للبداية",
        "align.prevEmpty": "انتقل إلى الترجمة الفارغة السابقة",
        "align.prev": "السابق",
        "align.next": "التالي",
        "align.nextEmpty": "انتقل إلى الترجمة الفارغة التالية",
        "align.goToEnd": "الذهاب للنهاية",
        "align.saveResult": "حفظ النتيجة",
        "align.typeSubtitle": "اكتب الترجمة هنا...",
        "align.noSubtitle": "لا يوجد ترجمة"
    },
    "de": {
        "align.baseSrt": "Original / Basis-SRT",
        "align.openSrt": "SRT öffnen",
        "align.dragDropSrt": "SRT hierhin ziehen & ablegen...",
        "align.subtitlesLoaded": "{{count}} Untertitel geladen",
        "align.swapFiles": "Dateireihenfolge tauschen",
        "align.translationSrt": "Übersetzung / Überprüfungs-SRT",
        "align.loadPrompt": "Laden Sie einige SRT-Dateien, um mit dem Ausrichten zu beginnen.",
        "align.dragDropAnywhere": "Sie können Dateien überall in diesem Fenster ziehen und ablegen.",
        "align.page": "Seite",
        "align.of": "von",
        "align.subsPerPage": "{{count}} Untertitel pro Seite",
        "align.goToStart": "Zum Anfang",
        "align.prevEmpty": "Zum vorherigen leeren Untertitel springen",
        "align.prev": "Zurück",
        "align.next": "Weiter",
        "align.nextEmpty": "Zum nächsten leeren Untertitel springen",
        "align.goToEnd": "Zum Ende",
        "align.saveResult": "Ergebnis speichern",
        "align.typeSubtitle": "Untertitel hier eingeben...",
        "align.noSubtitle": "Kein Untertitel"
    },
    "es": {
        "align.baseSrt": "Original / SRT base",
        "align.openSrt": "Abrir SRT",
        "align.dragDropSrt": "Arrastra y suelta el SRT aquí...",
        "align.subtitlesLoaded": "{{count}} subtítulos cargados",
        "align.swapFiles": "Intercambiar orden de archivos",
        "align.translationSrt": "Traducción / Revisión de SRT",
        "align.loadPrompt": "Cargue algunos archivos SRT para comenzar a alinear.",
        "align.dragDropAnywhere": "Puede arrastrar y soltar archivos en cualquier lugar de esta ventana.",
        "align.page": "Página",
        "align.of": "de",
        "align.subsPerPage": "{{count}} subtítulos por página",
        "align.goToStart": "Ir al inicio",
        "align.prevEmpty": "Saltar al subtítulo vacío anterior",
        "align.prev": "Anterior",
        "align.next": "Siguiente",
        "align.nextEmpty": "Saltar al siguiente subtítulo vacío",
        "align.goToEnd": "Ir al final",
        "align.saveResult": "Guardar resultado",
        "align.typeSubtitle": "Escriba el subtítulo aquí...",
        "align.noSubtitle": "Sin subtítulo"
    },
    "fr": {
        "align.baseSrt": "Original / SRT de base",
        "align.openSrt": "Ouvrir SRT",
        "align.dragDropSrt": "Glissez et déposez le SRT ici...",
        "align.subtitlesLoaded": "{{count}} sous-titres chargés",
        "align.swapFiles": "Inverser l'ordre des fichiers",
        "align.translationSrt": "Traduction / Révision SRT",
        "align.loadPrompt": "Chargez des fichiers SRT pour commencer l'alignement.",
        "align.dragDropAnywhere": "Vous pouvez glisser-déposer des fichiers n'importe où sur cette fenêtre.",
        "align.page": "Page",
        "align.of": "sur",
        "align.subsPerPage": "{{count}} sous-titres par page",
        "align.goToStart": "Aller au début",
        "align.prevEmpty": "Passer au sous-titre vide précédent",
        "align.prev": "Précédent",
        "align.next": "Suivant",
        "align.nextEmpty": "Passer au sous-titre vide suivant",
        "align.goToEnd": "Aller à la fin",
        "align.saveResult": "Enregistrer le résultat",
        "align.typeSubtitle": "Tapez le sous-titre ici...",
        "align.noSubtitle": "Pas de sous-titre"
    },
    "hi": {
        "align.baseSrt": "मूल / बेस SRT",
        "align.openSrt": "SRT खोलें",
        "align.dragDropSrt": "SRT यहाँ खींचें और छोड़ें...",
        "align.subtitlesLoaded": "{{count}} उपशीर्षक लोड किए गए",
        "align.swapFiles": "फ़ाइल क्रम बदलें",
        "align.translationSrt": "अनुवाद / समीक्षा SRT",
        "align.loadPrompt": "संरेखण शुरू करने के लिए कुछ SRT फ़ाइलें लोड करें।",
        "align.dragDropAnywhere": "आप इस विंडो पर कहीं भी फ़ाइलें खींच और छोड़ सकते हैं।",
        "align.page": "पृष्ठ",
        "align.of": "में से",
        "align.subsPerPage": "{{count}} उपशीर्षक प्रति पृष्ठ",
        "align.goToStart": "प्रारंभ पर जाएं",
        "align.prevEmpty": "पिछले खाली उपशीर्षक पर जाएं",
        "align.prev": "पिछला",
        "align.next": "अगला",
        "align.nextEmpty": "अगले खाली उपशीर्षक पर जाएं",
        "align.goToEnd": "अंत पर जाएं",
        "align.saveResult": "परिणाम सहेजें",
        "align.typeSubtitle": "यहाँ उपशीर्षक टाइप करें...",
        "align.noSubtitle": "कोई उपशीर्षक नहीं"
    },
    "ja": {
        "align.baseSrt": "オリジナル / ベース SRT",
        "align.openSrt": "SRT を開く",
        "align.dragDropSrt": "ここに SRT をドラッグ＆ドロップ...",
        "align.subtitlesLoaded": "{{count}} 個の字幕が読み込まれました",
        "align.swapFiles": "ファイルの順序を入れ替える",
        "align.translationSrt": "翻訳 / レビュー SRT",
        "align.loadPrompt": "アライメントを開始するには、SRTファイルを読み込んでください。",
        "align.dragDropAnywhere": "このウィンドウのどこにでもファイルをドラッグ＆ドロップできます。",
        "align.page": "ページ",
        "align.of": "/",
        "align.subsPerPage": "1ページあたり {{count}} 個の字幕",
        "align.goToStart": "最初に戻る",
        "align.prevEmpty": "前の空の字幕にジャンプ",
        "align.prev": "前へ",
        "align.next": "次へ",
        "align.nextEmpty": "次の空の字幕にジャンプ",
        "align.goToEnd": "最後まで行く",
        "align.saveResult": "結果を保存",
        "align.typeSubtitle": "ここに字幕を入力...",
        "align.noSubtitle": "字幕なし"
    },
    "ko": {
        "align.baseSrt": "원본 / 기본 SRT",
        "align.openSrt": "SRT 열기",
        "align.dragDropSrt": "여기에 SRT를 드래그 앤 드롭...",
        "align.subtitlesLoaded": "{{count}}개 자막 로드됨",
        "align.swapFiles": "파일 순서 바꾸기",
        "align.translationSrt": "번역 / 검토 SRT",
        "align.loadPrompt": "정렬을 시작하려면 SRT 파일을 로드하세요.",
        "align.dragDropAnywhere": "이 창 아무 곳에나 파일을 드래그 앤 드롭할 수 있습니다.",
        "align.page": "페이지",
        "align.of": "/",
        "align.subsPerPage": "페이지당 {{count}}개 자막",
        "align.goToStart": "처음으로 이동",
        "align.prevEmpty": "이전 빈 자막으로 점프",
        "align.prev": "이전",
        "align.next": "다음",
        "align.nextEmpty": "다음 빈 자막으로 점프",
        "align.goToEnd": "끝으로 이동",
        "align.saveResult": "결과 저장",
        "align.typeSubtitle": "여기에 자막 입력...",
        "align.noSubtitle": "자막 없음"
    },
    "nl": {
        "align.baseSrt": "Originele / basis-SRT",
        "align.openSrt": "SRT openen",
        "align.dragDropSrt": "Sleep SRT hierheen...",
        "align.subtitlesLoaded": "{{count}} ondertitels geladen",
        "align.swapFiles": "Bestandsvolgorde wisselen",
        "align.translationSrt": "Vertaling / revisie-SRT",
        "align.loadPrompt": "Laad enkele SRT-bestanden om te beginnen met uitlijnen.",
        "align.dragDropAnywhere": "Je kunt bestanden overal in dit venster slepen en neerzetten.",
        "align.page": "Pagina",
        "align.of": "van",
        "align.subsPerPage": "{{count}} ondertitels per pagina",
        "align.goToStart": "Naar begin",
        "align.prevEmpty": "Ga naar vorige lege ondertitel",
        "align.prev": "Vorige",
        "align.next": "Volgende",
        "align.nextEmpty": "Ga naar volgende lege ondertitel",
        "align.goToEnd": "Naar einde",
        "align.saveResult": "Resultaat opslaan",
        "align.typeSubtitle": "Typ hier de ondertitel...",
        "align.noSubtitle": "Geen ondertitel"
    },
    "pl": {
        "align.baseSrt": "Oryginał / Bazowy SRT",
        "align.openSrt": "Otwórz SRT",
        "align.dragDropSrt": "Przeciągnij i upuść SRT tutaj...",
        "align.subtitlesLoaded": "Wczytano {{count}} napisów",
        "align.swapFiles": "Zamień kolejność plików",
        "align.translationSrt": "Tłumaczenie / Rewizja SRT",
        "align.loadPrompt": "Wczytaj pliki SRT, aby rozpocząć wyrównywanie.",
        "align.dragDropAnywhere": "Możesz przeciągać i upuszczać pliki w dowolnym miejscu tego okna.",
        "align.page": "Strona",
        "align.of": "z",
        "align.subsPerPage": "{{count}} napisów na stronę",
        "align.goToStart": "Przejdź na początek",
        "align.prevEmpty": "Skocz do poprzednich pustych napisów",
        "align.prev": "Poprzednia",
        "align.next": "Następna",
        "align.nextEmpty": "Skocz do następnych pustych napisów",
        "align.goToEnd": "Przejdź na koniec",
        "align.saveResult": "Zapisz wynik",
        "align.typeSubtitle": "Wpisz napisy tutaj...",
        "align.noSubtitle": "Brak napisów"
    },
    "pt": {
        "align.baseSrt": "Original / SRT base",
        "align.openSrt": "Abrir SRT",
        "align.dragDropSrt": "Arraste e solte o SRT aqui...",
        "align.subtitlesLoaded": "{{count}} legendas carregadas",
        "align.swapFiles": "Inverter ordem dos arquivos",
        "align.translationSrt": "Tradução / Revisão SRT",
        "align.loadPrompt": "Carregue alguns arquivos SRT para começar a alinhar.",
        "align.dragDropAnywhere": "Você pode arrastar e soltar arquivos em qualquer lugar desta janela.",
        "align.page": "Página",
        "align.of": "de",
        "align.subsPerPage": "{{count}} legendas por página",
        "align.goToStart": "Ir para o início",
        "align.prevEmpty": "Pular para a legenda vazia anterior",
        "align.prev": "Anterior",
        "align.next": "Próxima",
        "align.nextEmpty": "Pular para a próxima legenda vazia",
        "align.goToEnd": "Ir para o final",
        "align.saveResult": "Salvar resultado",
        "align.typeSubtitle": "Digite a legenda aqui...",
        "align.noSubtitle": "Sem legenda"
    },
    "ru": {
        "align.baseSrt": "Оригинал / Базовый SRT",
        "align.openSrt": "Открыть SRT",
        "align.dragDropSrt": "Перетащите SRT сюда...",
        "align.subtitlesLoaded": "Загружено субтитров: {{count}}",
        "align.swapFiles": "Поменять порядок файлов",
        "align.translationSrt": "Перевод / Редактура SRT",
        "align.loadPrompt": "Загрузите файлы SRT, чтобы начать синхронизацию.",
        "align.dragDropAnywhere": "Вы можете перетаскивать файлы в любое место этого окна.",
        "align.page": "Страница",
        "align.of": "из",
        "align.subsPerPage": "Субтитров на страницу: {{count}}",
        "align.goToStart": "В начало",
        "align.prevEmpty": "Перейти к предыдущему пустому субтитру",
        "align.prev": "Назад",
        "align.next": "Вперед",
        "align.nextEmpty": "Перейти к следующему пустому субтитру",
        "align.goToEnd": "В конец",
        "align.saveResult": "Сохранить результат",
        "align.typeSubtitle": "Введите субтитр здесь...",
        "align.noSubtitle": "Нет субтитра"
    },
    "tr": {
        "align.baseSrt": "Orijinal / Temel SRT",
        "align.openSrt": "SRT Aç",
        "align.dragDropSrt": "SRT'yi buraya sürükleyip bırakın...",
        "align.subtitlesLoaded": "{{count}} altyazı yüklendi",
        "align.swapFiles": "Dosya sırasını değiştir",
        "align.translationSrt": "Çeviri / İnceleme SRT",
        "align.loadPrompt": "Hizalamaya başlamak için birkaç SRT dosyası yükleyin.",
        "align.dragDropAnywhere": "Dosyaları bu pencerenin herhangi bir yerine sürükleyip bırakabilirsiniz.",
        "align.page": "Sayfa",
        "align.of": "/",
        "align.subsPerPage": "Sayfa başına {{count}} altyazı",
        "align.goToStart": "Başa git",
        "align.prevEmpty": "Önceki boş altyazıya atla",
        "align.prev": "Önceki",
        "align.next": "Sonraki",
        "align.nextEmpty": "Sonraki boş altyazıya atla",
        "align.goToEnd": "Sona git",
        "align.saveResult": "Sonucu kaydet",
        "align.typeSubtitle": "Altyazıyı buraya yazın...",
        "align.noSubtitle": "Altyazı yok"
    },
    "zh": {
        "align.baseSrt": "原文 / 基础 SRT",
        "align.openSrt": "打开 SRT",
        "align.dragDropSrt": "将 SRT 拖放到此处...",
        "align.subtitlesLoaded": "已加载 {{count}} 个字幕",
        "align.swapFiles": "交换文件顺序",
        "align.translationSrt": "翻译 / 修订 SRT",
        "align.loadPrompt": "加载一些 SRT 文件以开始对齐。",
        "align.dragDropAnywhere": "您可以将文件拖放到此窗口的任何位置。",
        "align.page": "页",
        "align.of": "/",
        "align.subsPerPage": "每页 {{count}} 个字幕",
        "align.goToStart": "回到开始",
        "align.prevEmpty": "跳到上一个空字幕",
        "align.prev": "上一页",
        "align.next": "下一页",
        "align.nextEmpty": "跳到下一个空字幕",
        "align.goToEnd": "到底部",
        "align.saveResult": "保存结果",
        "align.typeSubtitle": "在此输入字幕...",
        "align.noSubtitle": "无字幕"
    }
}

for locale, data in translations.items():
    file_path = os.path.join(locales_dir, f"{locale}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = json.load(f)
        content.update(data)
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(content, f, ensure_ascii=False, indent=2)

print("Translations applied successfully!")
